version: '3.8'
services:

  web_sf_3:
    build:
      context: .
    environment:
      - VITE_API=${VITE_API}
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - VIRTUAL_PORT=${VIRTUAL_PORT}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
    ports:
      - 8086:80

networks:
  default:
    name: base_red_pme
    external: true